import Head from "next/head";

import Menu from "../components/Menu";
import BtonTop from "../components/btonTop";
import Spinner from "../components/spinner";
import Contact from "../components/seccion/about";

import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);

  const handleLoadingComplete = () => {
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>ZZU Gym</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ico.svg" />
        <meta name="theme-color" content="#000000" />
      </Head>
{/* 
      {loading && <Spinner />} */}
      <main>
        <Menu />
        <Contact />
        <BtonTop />
      </main>
    </div>
  );
}
