import Head from "next/head";

import Inicio from "../components/seccion/Inicio";
import Instructores from "../components/seccion/Instructores";
import Ofertas from "../components/seccion/Ofertas";
import Planes from "../components/seccion/Planes";
import Imc from "../components/seccion/Imc";
import Contacto from "../components/seccion/Contacto";
import Menu from "../components/Menu";
import BtonTop from "../components/btonTop";
import Spinner from "../components/spinner";

import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);

  const handleLoadingComplete = () => {
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>ZZU Gym</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/ico.svg" />
        <meta name="theme-color" content="#000000" />
      </Head>

      {loading && <Spinner />}
      <main>
        <Menu />
        <Inicio onLoadingComplete={handleLoadingComplete} />
        <Ofertas />
        <Planes />
        <Instructores />
        <Imc />
        <Contacto />

        <BtonTop />
      </main>
    </div>
  );
}
